services:
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    image: nlp-lab2-mlflow:latest
    container_name: nlp-lab2-mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}
      MLFLOW_ARTIFACT_ROOT: ${MLFLOW_ARTIFACT_ROOT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    image: nlp-lab2-api:latest
    container_name: nlp-lab2-api
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      MLFLOW_EXPERIMENT_NAME: nlp-lab2-sentiment140
      MLFLOW_REGISTERED_MODEL_NAME: sentiment140
      MLFLOW_MODEL_ALIAS: champion
    depends_on:
      - mlflow
    restart: unless-stopped
